-- Generated by Oracle SQL Developer Data Modeler 19.4.0.350.1424
--   at:        2020-03-12 14:46:35 CLST
--   site:      Oracle Database 11g
--   type:      Oracle Database 11g



CREATE TABLE alternativas (
    alternativa_id  INTEGER NOT NULL,
    descripcion     VARCHAR2(250 CHAR) NOT NULL,
    correcta        CHAR(1) NOT NULL,
    porcentaje      FLOAT NOT NULL,
    pregunta_id     INTEGER NOT NULL
);

ALTER TABLE alternativas ADD CONSTRAINT alternativas_pk PRIMARY KEY ( alternativa_id );

CREATE TABLE alumnos (
    alumno_id  INTEGER NOT NULL,
    nombre     VARCHAR2(150 CHAR) NOT NULL,
    curso_id   INTEGER NOT NULL
);

ALTER TABLE alumnos ADD CONSTRAINT alumnos_pk PRIMARY KEY ( alumno_id );

CREATE TABLE curso_evaluacion (
    curso_id       INTEGER NOT NULL,
    evaluacion_id  INTEGER NOT NULL
);

ALTER TABLE curso_evaluacion ADD CONSTRAINT curso_evaluacion_pk PRIMARY KEY ( curso_id,
                                                                              evaluacion_id );

CREATE TABLE cursos (
    curso_id      INTEGER NOT NULL,
    programa      VARCHAR2(100 CHAR) NOT NULL,
    hora_entrada  DATE NOT NULL,
    hora_salida   DATE NOT NULL
);

ALTER TABLE cursos ADD CONSTRAINT cursos_pk PRIMARY KEY ( curso_id );

CREATE TABLE evaluaciones (
    evaluacion_id  INTEGER NOT NULL,
    nombre         VARCHAR2(50 CHAR) NOT NULL,
    descripcion    CLOB NOT NULL,
    unidad         VARCHAR2(50 CHAR) NOT NULL,
    autor          VARCHAR2(100 CHAR) NOT NULL,
    fecha          DATE NOT NULL
);

ALTER TABLE evaluaciones ADD CONSTRAINT evaluaciones_pk PRIMARY KEY ( evaluacion_id );

CREATE TABLE preguntas (
    pregunta_id    INTEGER NOT NULL,
    enunciado      VARCHAR2(250 CHAR) NOT NULL,
    puntaje        INTEGER NOT NULL,
    evaluacion_id  INTEGER NOT NULL
);

ALTER TABLE preguntas ADD CONSTRAINT preguntas_pk PRIMARY KEY ( pregunta_id );

CREATE TABLE respuestas (
    respuesta_id    INTEGER NOT NULL,
    alumno_id       INTEGER NOT NULL,
    pregunta_id     INTEGER NOT NULL,
    alternativa_id  INTEGER NOT NULL
);

ALTER TABLE respuestas ADD CONSTRAINT respuestas_pk PRIMARY KEY ( respuesta_id );

ALTER TABLE respuestas
    ADD CONSTRAINT alternativas_fk FOREIGN KEY ( alternativa_id )
        REFERENCES alternativas ( alternativa_id );

ALTER TABLE respuestas
    ADD CONSTRAINT alumnos_fk FOREIGN KEY ( alumno_id )
        REFERENCES alumnos ( alumno_id );

ALTER TABLE alumnos
    ADD CONSTRAINT cursos_fk FOREIGN KEY ( curso_id )
        REFERENCES cursos ( curso_id );

ALTER TABLE curso_evaluacion
    ADD CONSTRAINT cursos_fkv1 FOREIGN KEY ( curso_id )
        REFERENCES cursos ( curso_id );

ALTER TABLE preguntas
    ADD CONSTRAINT evaluaciones_fk FOREIGN KEY ( evaluacion_id )
        REFERENCES evaluaciones ( evaluacion_id );

ALTER TABLE curso_evaluacion
    ADD CONSTRAINT evaluaciones_fkv1 FOREIGN KEY ( evaluacion_id )
        REFERENCES evaluaciones ( evaluacion_id );

ALTER TABLE alternativas
    ADD CONSTRAINT preguntas_fk FOREIGN KEY ( pregunta_id )
        REFERENCES preguntas ( pregunta_id );

ALTER TABLE respuestas
    ADD CONSTRAINT preguntas_fkv1 FOREIGN KEY ( pregunta_id )
        REFERENCES preguntas ( pregunta_id );

CREATE SEQUENCE alternativas_alternativa_id START WITH 1 NOCACHE ORDER;

CREATE OR REPLACE TRIGGER alternativas_alternativa_id BEFORE
    INSERT ON alternativas
    FOR EACH ROW
    WHEN ( new.alternativa_id IS NULL )
BEGIN
    :new.alternativa_id := alternativas_alternativa_id.nextval;
END;
/

CREATE SEQUENCE alumnos_alumno_id_seq START WITH 1 NOCACHE ORDER;

CREATE OR REPLACE TRIGGER alumnos_alumno_id_trg BEFORE
    INSERT ON alumnos
    FOR EACH ROW
    WHEN ( new.alumno_id IS NULL )
BEGIN
    :new.alumno_id := alumnos_alumno_id_seq.nextval;
END;
/

CREATE SEQUENCE cursos_curso_id_seq START WITH 1 NOCACHE ORDER;

CREATE OR REPLACE TRIGGER cursos_curso_id_trg BEFORE
    INSERT ON cursos
    FOR EACH ROW
    WHEN ( new.curso_id IS NULL )
BEGIN
    :new.curso_id := cursos_curso_id_seq.nextval;
END;
/

CREATE SEQUENCE evaluaciones_evaluacion_id_seq START WITH 1 NOCACHE ORDER;

CREATE OR REPLACE TRIGGER evaluaciones_evaluacion_id_trg BEFORE
    INSERT ON evaluaciones
    FOR EACH ROW
    WHEN ( new.evaluacion_id IS NULL )
BEGIN
    :new.evaluacion_id := evaluaciones_evaluacion_id_seq.nextval;
END;
/

CREATE SEQUENCE preguntas_pregunta_id_seq START WITH 1 NOCACHE ORDER;

CREATE OR REPLACE TRIGGER preguntas_pregunta_id_trg BEFORE
    INSERT ON preguntas
    FOR EACH ROW
    WHEN ( new.pregunta_id IS NULL )
BEGIN
    :new.pregunta_id := preguntas_pregunta_id_seq.nextval;
END;
/

CREATE SEQUENCE respuestas_respuesta_id_seq START WITH 1 NOCACHE ORDER;

CREATE OR REPLACE TRIGGER respuestas_respuesta_id_trg BEFORE
    INSERT ON respuestas
    FOR EACH ROW
    WHEN ( new.respuesta_id IS NULL )
BEGIN
    :new.respuesta_id := respuestas_respuesta_id_seq.nextval;
END;
/



-- Oracle SQL Developer Data Modeler Summary Report: 
-- 
-- CREATE TABLE                             7
-- CREATE INDEX                             0
-- ALTER TABLE                             15
-- CREATE VIEW                              0
-- ALTER VIEW                               0
-- CREATE PACKAGE                           0
-- CREATE PACKAGE BODY                      0
-- CREATE PROCEDURE                         0
-- CREATE FUNCTION                          0
-- CREATE TRIGGER                           6
-- ALTER TRIGGER                            0
-- CREATE COLLECTION TYPE                   0
-- CREATE STRUCTURED TYPE                   0
-- CREATE STRUCTURED TYPE BODY              0
-- CREATE CLUSTER                           0
-- CREATE CONTEXT                           0
-- CREATE DATABASE                          0
-- CREATE DIMENSION                         0
-- CREATE DIRECTORY                         0
-- CREATE DISK GROUP                        0
-- CREATE ROLE                              0
-- CREATE ROLLBACK SEGMENT                  0
-- CREATE SEQUENCE                          6
-- CREATE MATERIALIZED VIEW                 0
-- CREATE MATERIALIZED VIEW LOG             0
-- CREATE SYNONYM                           0
-- CREATE TABLESPACE                        0
-- CREATE USER                              0
-- 
-- DROP TABLESPACE                          0
-- DROP DATABASE                            0
-- 
-- REDACTION POLICY                         0
-- 
-- ORDS DROP SCHEMA                         0
-- ORDS ENABLE SCHEMA                       0
-- ORDS ENABLE OBJECT                       0
-- 
-- ERRORS                                   0
-- WARNINGS                                 0
