-- Generated by Oracle SQL Developer Data Modeler 19.4.0.350.1424
--   at:        2020-03-10 23:51:52 CLST
--   site:      Oracle Database 11g
--   type:      Oracle Database 11g



CREATE TABLE articulos (
    articulo_id  INTEGER NOT NULL,
    nombre       VARCHAR2(50 CHAR),
    descripcion  VARCHAR2(250) NOT NULL
);

ALTER TABLE articulos ADD CONSTRAINT articulos_pk PRIMARY KEY ( articulo_id );

CREATE TABLE clientes (
    cliente_id  INTEGER NOT NULL,
    nombre      VARCHAR2(150 CHAR),
    credito     INTEGER DEFAULT 0,
    descuento   NUMBER DEFAULT 0
);

ALTER TABLE clientes ADD CONSTRAINT clientes_pk PRIMARY KEY ( cliente_id );

CREATE TABLE detalles (
    detalle_id             INTEGER NOT NULL,
    cantidad               INTEGER NOT NULL,
    pedido_id              INTEGER NOT NULL,
    articulo_id            INTEGER NOT NULL
);

ALTER TABLE detalles ADD CONSTRAINT detalles_pk PRIMARY KEY ( detalle_id );

CREATE TABLE direcciones (
    direccion_id         INTEGER NOT NULL,
    calle                VARCHAR2(100 CHAR) NOT NULL,
    numero               VARCHAR2(10 CHAR) NOT NULL,
    comuna               VARCHAR2(50 CHAR) NOT NULL,
    ciudad               VARCHAR2(50 CHAR) NOT NULL,
    cliente_id           INTEGER NOT NULL
);

ALTER TABLE direcciones ADD CONSTRAINT direcciones_pk PRIMARY KEY ( direccion_id );

CREATE TABLE fabricas (
    fabrica_id             INTEGER NOT NULL,
    nombre                 VARCHAR2(100 CHAR),
    telefono               VARCHAR2(20 CHAR) NOT NULL,
    articulo_id            INTEGER NOT NULL
);

ALTER TABLE fabricas ADD CONSTRAINT fabrica_pk PRIMARY KEY ( fabrica_id );

CREATE TABLE pedidos (
    pedido_id            INTEGER NOT NULL,
    fecha                DATE NOT NULL,
    direccion_id         INTEGER NOT NULL,
    cliente_id           INTEGER NOT NULL
);

ALTER TABLE pedidos ADD CONSTRAINT pedidos_pk PRIMARY KEY ( pedido_id );

ALTER TABLE detalles
    ADD CONSTRAINT detalles_articulo FOREIGN KEY ( articulo_id )
        REFERENCES articulos ( articulo_id );

ALTER TABLE detalles
    ADD CONSTRAINT detalles_pedido FOREIGN KEY ( pedido_id )
        REFERENCES pedidos ( pedido_id );

ALTER TABLE direcciones
    ADD CONSTRAINT direccion_cliente FOREIGN KEY ( cliente_id )
        REFERENCES clientes ( cliente_id );

ALTER TABLE fabricas
    ADD CONSTRAINT fabrica_articulo FOREIGN KEY ( articulo_id )
        REFERENCES articulos ( articulo_id );

ALTER TABLE pedidos
    ADD CONSTRAINT pedido_cliente FOREIGN KEY ( cliente_id )
        REFERENCES clientes ( cliente_id );

ALTER TABLE pedidos
    ADD CONSTRAINT pedido_direccion FOREIGN KEY ( direccion_id )
        REFERENCES direcciones ( direccion_id );

CREATE SEQUENCE articulos_articulo_id_seq START WITH 1 NOCACHE ORDER;

CREATE OR REPLACE TRIGGER articulos_articulo_id_trg BEFORE
    INSERT ON articulos
    FOR EACH ROW
    WHEN ( new.articulo_id IS NULL )
BEGIN
    :new.articulo_id := articulos_articulo_id_seq.nextval;
END;
/

CREATE SEQUENCE clientes_cliente_id_seq START WITH 1 NOCACHE ORDER;

CREATE OR REPLACE TRIGGER clientes_cliente_id_trg BEFORE
    INSERT ON clientes
    FOR EACH ROW
    WHEN ( new.cliente_id IS NULL )
BEGIN
    :new.cliente_id := clientes_cliente_id_seq.nextval;
END;
/

CREATE SEQUENCE detalles_detalle_id_seq START WITH 1 NOCACHE ORDER;

CREATE OR REPLACE TRIGGER detalles_detalle_id_trg BEFORE
    INSERT ON detalles
    FOR EACH ROW
    WHEN ( new.detalle_id IS NULL )
BEGIN
    :new.detalle_id := detalles_detalle_id_seq.nextval;
END;
/

CREATE SEQUENCE direcciones_direccion_id_seq START WITH 1 NOCACHE ORDER;

CREATE OR REPLACE TRIGGER direcciones_direccion_id_trg BEFORE
    INSERT ON direcciones
    FOR EACH ROW
    WHEN ( new.direccion_id IS NULL )
BEGIN
    :new.direccion_id := direcciones_direccion_id_seq.nextval;
END;
/

CREATE SEQUENCE fabricas_fabrica_id_seq START WITH 1 NOCACHE ORDER;

CREATE OR REPLACE TRIGGER fabricas_fabrica_id_trg BEFORE
    INSERT ON fabricas
    FOR EACH ROW
    WHEN ( new.fabrica_id IS NULL )
BEGIN
    :new.fabrica_id := fabricas_fabrica_id_seq.nextval;
END;
/

CREATE SEQUENCE pedidos_pedido_id_seq START WITH 1 NOCACHE ORDER;

CREATE OR REPLACE TRIGGER pedidos_pedido_id_trg BEFORE
    INSERT ON pedidos
    FOR EACH ROW
    WHEN ( new.pedido_id IS NULL )
BEGIN
    :new.pedido_id := pedidos_pedido_id_seq.nextval;
END;
/



-- Oracle SQL Developer Data Modeler Summary Report: 
-- 
-- CREATE TABLE                             6
-- CREATE INDEX                             0
-- ALTER TABLE                             11
-- CREATE VIEW                              0
-- ALTER VIEW                               0
-- CREATE PACKAGE                           0
-- CREATE PACKAGE BODY                      0
-- CREATE PROCEDURE                         0
-- CREATE FUNCTION                          0
-- CREATE TRIGGER                           6
-- ALTER TRIGGER                            0
-- CREATE COLLECTION TYPE                   0
-- CREATE STRUCTURED TYPE                   0
-- CREATE STRUCTURED TYPE BODY              0
-- CREATE CLUSTER                           0
-- CREATE CONTEXT                           0
-- CREATE DATABASE                          0
-- CREATE DIMENSION                         0
-- CREATE DIRECTORY                         0
-- CREATE DISK GROUP                        0
-- CREATE ROLE                              0
-- CREATE ROLLBACK SEGMENT                  0
-- CREATE SEQUENCE                          6
-- CREATE MATERIALIZED VIEW                 0
-- CREATE MATERIALIZED VIEW LOG             0
-- CREATE SYNONYM                           0
-- CREATE TABLESPACE                        0
-- CREATE USER                              0
-- 
-- DROP TABLESPACE                          0
-- DROP DATABASE                            0
-- 
-- REDACTION POLICY                         0
-- 
-- ORDS DROP SCHEMA                         0
-- ORDS ENABLE SCHEMA                       0
-- ORDS ENABLE OBJECT                       0
-- 
-- ERRORS                                   0
-- WARNINGS                                 0
