-- Generated by Oracle SQL Developer Data Modeler 19.4.0.350.1424
--   at:        2020-03-09 18:26:19 CLST
--   site:      Oracle Database 11g
--   type:      Oracle Database 11g



CREATE TABLE comisarios (
    comisario_id       NUMBER NOT NULL,
    nombre             VARCHAR2(150 CHAR) NOT NULL,
    tarea              VARCHAR2(50 CHAR) NOT NULL,
    eventos_evento_id  NUMBER NOT NULL
);

ALTER TABLE comisarios ADD CONSTRAINT comisarios_pk PRIMARY KEY ( comisario_id );

CREATE TABLE complejos (
    complejo_id        NUMBER NOT NULL,
    localizacion       VARCHAR2(20 CHAR) NOT NULL,
    jefe_organizacion  VARCHAR2(150 CHAR) NOT NULL,
    area_ocupada       FLOAT(2) NOT NULL,
    tipo               VARCHAR2(6 CHAR) NOT NULL,
    sedes_sede_id      NUMBER NOT NULL
);

ALTER TABLE complejos ADD CONSTRAINT complejos_pk PRIMARY KEY ( complejo_id );

CREATE TABLE equipamientos (
    equipamiento_id    NUMBER NOT NULL,
    nombre             VARCHAR2(100 CHAR) NOT NULL,
    tipo               VARCHAR2(100 CHAR) NOT NULL,
    eventos_evento_id  NUMBER NOT NULL
);

ALTER TABLE equipamientos ADD CONSTRAINT equipamientos_pk PRIMARY KEY ( equipamiento_id );

CREATE TABLE eventos (
    evento_id              NUMBER NOT NULL,
    nombre                 VARCHAR2(100 CHAR),
    fecha                  DATE NOT NULL,
    duracion               INTEGER NOT NULL,
    qty_participantes      INTEGER NOT NULL,
    complejos_complejo_id  NUMBER NOT NULL
);

ALTER TABLE eventos ADD CONSTRAINT eventos_pk PRIMARY KEY ( evento_id );

CREATE TABLE sedes (
    sede_id      NUMBER NOT NULL,
    nombre       VARCHAR2(100 CHAR),
    presupuesto  FLOAT(2) NOT NULL
);

ALTER TABLE sedes ADD CONSTRAINT sedes_pk PRIMARY KEY ( sede_id );

ALTER TABLE comisarios
    ADD CONSTRAINT comisarios_eventos_fk FOREIGN KEY ( eventos_evento_id )
        REFERENCES eventos ( evento_id );

ALTER TABLE complejos
    ADD CONSTRAINT complejos_sedes_fk FOREIGN KEY ( sedes_sede_id )
        REFERENCES sedes ( sede_id );

ALTER TABLE equipamientos
    ADD CONSTRAINT equip_eventos_fk FOREIGN KEY ( eventos_evento_id )
        REFERENCES eventos ( evento_id );

ALTER TABLE eventos
    ADD CONSTRAINT eventos_complejos_fk FOREIGN KEY ( complejos_complejo_id )
        REFERENCES complejos ( complejo_id );

CREATE SEQUENCE comisarios_comisario_id_seq START WITH 1 NOCACHE ORDER;

CREATE OR REPLACE TRIGGER comisarios_comisario_id_trg BEFORE
    INSERT ON comisarios
    FOR EACH ROW
    WHEN ( new.comisario_id IS NULL )
BEGIN
    :new.comisario_id := comisarios_comisario_id_seq.nextval;
END;
/

CREATE SEQUENCE cdeportivos_complejo_id_seq START WITH 1 NOCACHE ORDER;

CREATE OR REPLACE TRIGGER cdeportivos_complejo_id_trg BEFORE
    INSERT ON complejos
    FOR EACH ROW
    WHEN ( new.complejo_id IS NULL )
BEGIN
    :new.complejo_id := cdeportivos_complejo_id_seq.nextval;
END;
/

CREATE SEQUENCE equipamientos_equipamiento_id START WITH 1 NOCACHE ORDER;

CREATE OR REPLACE TRIGGER equipamientos_equipamiento_id BEFORE
    INSERT ON equipamientos
    FOR EACH ROW
    WHEN ( new.equipamiento_id IS NULL )
BEGIN
    :new.equipamiento_id := equipamientos_equipamiento_id.nextval;
END;
/

CREATE SEQUENCE eventos_evento_id_seq START WITH 1 NOCACHE ORDER;

CREATE OR REPLACE TRIGGER eventos_evento_id_trg BEFORE
    INSERT ON eventos
    FOR EACH ROW
    WHEN ( new.evento_id IS NULL )
BEGIN
    :new.evento_id := eventos_evento_id_seq.nextval;
END;
/

CREATE SEQUENCE solimpicas_sede_id_seq START WITH 1 NOCACHE ORDER;

CREATE OR REPLACE TRIGGER solimpicas_sede_id_trg BEFORE
    INSERT ON sedes
    FOR EACH ROW
    WHEN ( new.sede_id IS NULL )
BEGIN
    :new.sede_id := solimpicas_sede_id_seq.nextval;
END;
/



-- Oracle SQL Developer Data Modeler Summary Report: 
-- 
-- CREATE TABLE                             5
-- CREATE INDEX                             0
-- ALTER TABLE                              9
-- CREATE VIEW                              0
-- ALTER VIEW                               0
-- CREATE PACKAGE                           0
-- CREATE PACKAGE BODY                      0
-- CREATE PROCEDURE                         0
-- CREATE FUNCTION                          0
-- CREATE TRIGGER                           5
-- ALTER TRIGGER                            0
-- CREATE COLLECTION TYPE                   0
-- CREATE STRUCTURED TYPE                   0
-- CREATE STRUCTURED TYPE BODY              0
-- CREATE CLUSTER                           0
-- CREATE CONTEXT                           0
-- CREATE DATABASE                          0
-- CREATE DIMENSION                         0
-- CREATE DIRECTORY                         0
-- CREATE DISK GROUP                        0
-- CREATE ROLE                              0
-- CREATE ROLLBACK SEGMENT                  0
-- CREATE SEQUENCE                          5
-- CREATE MATERIALIZED VIEW                 0
-- CREATE MATERIALIZED VIEW LOG             0
-- CREATE SYNONYM                           0
-- CREATE TABLESPACE                        0
-- CREATE USER                              0
-- 
-- DROP TABLESPACE                          0
-- DROP DATABASE                            0
-- 
-- REDACTION POLICY                         0
-- 
-- ORDS DROP SCHEMA                         0
-- ORDS ENABLE SCHEMA                       0
-- ORDS ENABLE OBJECT                       0
-- 
-- ERRORS                                   0
-- WARNINGS                                 0
